; ItemNames:
; 	db "大师球@"
; 	db "高级球@"
; 	db "超级球@"
; 	db "精灵球@"
; 	db "城镇地图@"
; 	db "自行车@"
; 	db "?????@"
; 	db "狩猎球@"
; 	db "宝可梦图鉴@"
; 	db "月之石@"
; 	db "解毒药@"
; 	db "灼伤药@"
; 	db "解冻药@"
; 	db "解眠药@"
; 	db "解麻药@"
; 	db "全复药@"
; 	db "全满药@"
; 	db "厉害伤药@"
; 	db "好伤药@"
; 	db "伤药@"
; 	db "灰色徽章@"
; 	db "蓝色徽章@"
; 	db "橙色徽章@"
; 	db "彩虹徽章@"
; 	db "粉红徽章@"
; 	db "金色徽章@"
; 	db "深红徽章@"
; 	db "绿色徽章@"
; 	db "离洞绳@"
; 	db "除虫喷雾@"
; 	db "秘密琥珀@"
; 	db "火之石@"
; 	db "雷之石@"
; 	db "水之石@"
; 	db "ＨＰ增强剂@"
; 	db "攻击增强剂@"
; 	db "防御增强剂@"
; 	db "速度增强剂@"
; 	db "特殊增强剂@"
; 	db "神奇糖果@"
; 	db "甲壳化石@"
; 	db "贝壳化石@"
; 	db "秘密钥匙@"
; 	db "?????@"
; 	db "兑换券@"
; 	db "命中强化@"
; 	db "叶之石@"
; 	db "钥匙卡@"
; 	db "金珠@"
; 	db "ＰＰ提升剂@"
; 	db "皮皮玩偶@"
; 	db "万灵药@"
; 	db "活力碎片@"
; 	db "活力块@"
; 	db "能力防守@"
; 	db "白银喷雾@"
; 	db "黄金喷雾@"
; 	db "要害攻击@"
; 	db "代币@"
; 	db "美味之水@"
; 	db "劲爽汽水@"
; 	db "果汁牛奶@"
; 	db "船票@"
; 	db "金假牙@"
; 	db "力量强化@"
; 	db "防御强化@"
; 	db "速度强化@"
; 	db "特殊强化@"
; 	db "代币盒@"
; 	db "包裹@"
; 	db "探宝器@"
; 	db "西尔佛检视镜@"
; 	db "宝可梦之笛@"
; 	db "电梯钥匙@"
; 	db "学习装置@"
; 	db "破旧钓竿@"
; 	db "好钓竿@"
; 	db "厉害钓竿@"
; 	db "ＰＰ提升剂@"
; 	db "PP单项小补剂@"
; 	db "PP单项全补剂@"
; 	db "PP多项小补剂@"
; 	db "PP多项全补剂@"
; 	db "地下2层@"
; 	db "地下1层@"
; 	db "1层@"
; 	db "2层@"
; 	db "3层@"
; 	db "4层@"
; 	db "5层@"
; 	db "6层@"
; 	db "7层@"
; 	db "8层@"
; 	db "9层@"
; 	db "10层@"
; 	db "11层@"
; 	db "地下4层@"

; ItemNames:
; 	db "MASTER BALL@"
; 	db "ULTRA BALL@"
; 	db "GREAT BALL@"
; 	db "POKé BALL@"
; 	db "TOWN MAP@"
; 	db "BICYCLE@"
; 	db "?????@"
; 	db "SAFARI BALL@"
; 	db "POKéDEX@"
; 	db "MOON STONE@"
; 	db "ANTIDOTE@"
; 	db "BURN HEAL@"
; 	db "ICE HEAL@"
; 	db "AWAKENING@"
; 	db "PARLYZ HEAL@"
; 	db "FULL RESTORE@"
; 	db "MAX POTION@"
; 	db "HYPER POTION@"
; 	db "SUPER POTION@"
; 	db "POTION@"
; 	db "BOULDERBADGE@"
; 	db "CASCADEBADGE@"
; 	db "THUNDERBADGE@"
; 	db "RAINBOWBADGE@"
; 	db "SOULBADGE@"
; 	db "MARSHBADGE@"
; 	db "VOLCANOBADGE@"
; 	db "EARTHBADGE@"
; 	db "ESCAPE ROPE@"
; 	db "REPEL@"
; 	db "OLD AMBER@"
; 	db "FIRE STONE@"
; 	db "THUNDERSTONE@"
; 	db "WATER STONE@"
; 	db "HP UP@"
; 	db "PROTEIN@"
; 	db "IRON@"
; 	db "CARBOS@"
; 	db "CALCIUM@"
; 	db "RARE CANDY@"
; 	db "DOME FOSSIL@"
; 	db "HELIX FOSSIL@"
; 	db "SECRET KEY@"
; 	db "?????@"
; 	db "BIKE VOUCHER@"
; 	db "X ACCURACY@"
; 	db "LEAF STONE@"
; 	db "CARD KEY@"
; 	db "NUGGET@"
; 	db "PP UP@"
; 	db "POKé DOLL@"
; 	db "FULL HEAL@"
; 	db "REVIVE@"
; 	db "MAX REVIVE@"
; 	db "GUARD SPEC.@"
; 	db "SUPER REPEL@"
; 	db "MAX REPEL@"
; 	db "DIRE HIT@"
; 	db "COIN@"
; 	db "FRESH WATER@"
; 	db "SODA POP@"
; 	db "LEMONADE@"
; 	db "S.S.TICKET@"
; 	db "GOLD TEETH@"
; 	db "X ATTACK@"
; 	db "X DEFEND@"
; 	db "X SPEED@"
; 	db "X SPECIAL@"
; 	db "COIN CASE@"
; 	db "OAK's PARCEL@"
; 	db "ITEMFINDER@"
; 	db "SILPH SCOPE@"
; 	db "POKé FLUTE@"
; 	db "LIFT KEY@"
; 	db "EXP.ALL@"
; 	db "OLD ROD@"
; 	db "GOOD ROD@"
; 	db "SUPER ROD@"
; 	db "PP UP@"
; 	db "ETHER@"
; 	db "MAX ETHER@"
; 	db "ELIXER@"
; 	db "MAX ELIXER@"
; 	db "B2F@"
; 	db "B1F@"
; 	db "1F@"
; 	db "2F@"
; 	db "3F@"
; 	db "4F@"
; 	db "5F@"
; 	db "6F@"
; 	db "7F@"
; 	db "8F@"
; 	db "9F@"
; 	db "10F@"
; 	db "11F@"
; 	db "B4F@"

ItemNames:
	db "大师球@"
	db "高级球@"
	db "超级球@"
	db "精灵球@"
	db "城镇地图@"
	db "自行车@"
	db "?????@"
	db "狩猎球@"
	db "宝可梦图鉴@"
	db "月之石@"
	db "解毒药@"
	db "灼伤药@"
	db "解冻药@"
	db "解眠药@"
	db "解麻药@"
	db "全复药@"
	db "全满药@"
	db "厉害伤药@"
	db "好伤药@"
	db "伤药@"
	db "灰色徽章@"
	db "蓝色徽章@"
	db "橙色徽章@"
	db "彩虹徽章@"
	db "粉红徽章@"
	db "金色徽章@"
	db "深红徽章@"
	db "绿色徽章@"
	db "离洞绳@"
	db "除虫喷雾@"
	db "秘密琥珀@"
	db "火之石@"
	db "雷之石@"
	db "水之石@"
	db $2E,$B8,"增强剂@"
	db "攻击增强剂@"
	db "防御增强剂@"
	db "速度增强剂@"
	db "特殊增强剂@"
	db "神奇糖果@"
	db "甲壳化石@"
	db "贝壳化石@"
	db "秘密钥匙@"
	db "?????@"
	db "兑换券@"
	db "命中强化@"
	db "叶之石@"
	db "钥匙卡@"
	db "金珠@"
	db $2E,$B8,"提升剂@"
	db "皮皮玩偶@"
	db "万灵药@"
	db "活力碎片@"
	db "活力块@"
	db "能力防守@"
	db "白银喷雾@"
	db "黄金喷雾@"
	db "要害攻击@"
	db "代币@"
	db "美味之水@"
	db "劲爽汽水@"
	db "果汁牛奶@"
	db "船票@"
	db "金假牙@"
	db "力量强化@"
	db "防御强化@"
	db "速度强化@"
	db "特殊强化@"
	db "代币盒@"
	db "包裹@"
	db "探宝器@"
	db "西尔佛检视镜@"
	db "宝可梦之笛@"
	db "电梯钥匙@"
	db "学习装置@"
	db "破旧钓竿@"
	db "好钓竿@"
	db "厉害钓竿@"
	db $2E,$B8,"提升剂@"
	db $2E,$B8,"单项小补剂@"
	db $2E,$B8,"单项全补剂@"
	db $2E,$B8,"多项小补剂@"
	db $2E,$B8,"多项全补剂@"
	db "地下2层@"
	db "地下1层@"
	db "1层@"
	db "2层@"
	db "3层@"
	db "4层@"
	db "5层@"
	db "6层@"
	db "7层@"
	db "8层@"
	db "9层@"
	db "10层@"
	db "11层@"
	db "地下4层@"